#!/usr/bin/env python3
"""Generate `data` for autocomp_fused_qkv_rope_d64.

Fused whole-Radiance kernel:  out[M,N] (bf16) = RoPE( bf16( X[M,K] @ W[K,N] ) )
  - MX-Gemmini fp4 matmul (K=2048) leaves C(bf16) in SMEM (no DRAM round-trip)
  - a 4-warp SIMT RoPE epilogue reads C from SMEM and writes rotated bf16 to GMEM

head_dim = N = 64  ->  HALF = 32 within the single head.
Golden = RoPE(mx_golden(X@W)), bit-exact: bf16 truncation + float32 RoPE math matches the
kernel exactly (no division in RoPE, so no divider-approximation divergence).
"""
import pathlib
import subprocess

import numpy as np

HERE = pathlib.Path(__file__).resolve().parent
MX_GOLDEN = pathlib.Path("/scratch/agustin/projects/autocomp/scripts/muon/mx_golden/mx_golden")
GROUP = 32
FP4_CODE = 2

M, N, K = 64, 64, 2048          # head_dim=64, model dim K=2048
HALF = N // 2                   # 32
THETA = 10000.0


def rand_fp4(rng, n):
    """fp4 e2m1 nibbles, |value| <= 1.5 (exp field <= 1) -- keeps partial sums bounded."""
    exp = rng.integers(0, 2, size=n, dtype=np.uint8)
    mant = rng.integers(0, 2, size=n, dtype=np.uint8)
    sign = rng.integers(0, 2, size=n, dtype=np.uint8)
    return ((sign << 3) | (exp << 1) | mant).astype(np.uint8)


def pack_axis0(x):  # [R,C] nibbles -> [R/2,C] bytes; even row low nibble
    return ((x[1::2, :] << 4) | (x[0::2, :] & 0xF)).astype(np.uint8)


def pack_axis1(x):  # [R,C] nibbles -> [R,C/2] bytes; even col low nibble
    return ((x[:, 1::2] << 4) | (x[:, 0::2] & 0xF)).astype(np.uint8)


def bf16_to_f32(u16):
    return (u16.astype(np.uint32) << 16).view(np.float32)


def f32_to_bf16_trunc(f):
    return (f.astype(np.float32).view(np.uint32) >> 16).astype(np.uint16)


def emit(f, ctype, name, dims, arr):
    w = 2 if ctype == "uint8_t" else (4 if ctype in ("uint16_t", "uint32_t") else 8)
    # uint16_t bf16 -> 4 hex; uint32_t float bits -> 8 hex
    w = {"uint8_t": 2, "uint16_t": 4, "uint32_t": 8}[ctype]
    rows = ["    " + ", ".join(f"0x{v:0{w}x}" for v in row) for row in arr]
    f.write(f"static const {ctype} {name}{dims} = {{\n")
    f.write(",\n".join(rows))
    f.write("\n};\n")


def main():
    GK, GN = K // GROUP, N // GROUP
    rng = np.random.default_rng(0xC0FFEE)

    A_nib = rand_fp4(rng, M * K).reshape(M, K)
    B_nib = rand_fp4(rng, K * N).reshape(K, N)
    A_hw = pack_axis0(A_nib)   # [M/2][K]
    B_in = pack_axis1(B_nib)   # [K][N/2]
    SA = rng.integers(0x7B, 0x83, size=(GK, M), dtype=np.uint8)
    SB = rng.integers(0x7B, 0x83, size=(GK, N), dtype=np.uint8)

    tmp = HERE / "_gen"
    tmp.mkdir(exist_ok=True)
    (tmp / "A.bin").write_bytes(A_hw.tobytes())
    (tmp / "B.bin").write_bytes(B_in.tobytes())
    (tmp / "SA.bin").write_bytes(SA.tobytes())
    (tmp / "SB.bin").write_bytes(SB.tobytes())

    subprocess.run(
        [str(MX_GOLDEN), str(M), str(N), str(K), str(tmp / "A.bin"), str(tmp / "B.bin"),
         str(tmp / "SA.bin"), str(tmp / "SB.bin"), str(tmp / "C.bin"), str(FP4_CODE)],
        check=True, env={"PATH": "/usr/bin:/bin"})
    C_bf16 = np.frombuffer((tmp / "C.bin").read_bytes(), dtype="<u2")[: M * N].reshape(M, N)

    # RoPE cos/sin caches (HF Llama style, duplicated across the two halves).
    inv_freq = (THETA ** (-(np.arange(0, HALF, dtype=np.float64) * 2.0 / N)))  # [HALF]
    pos = np.arange(M, dtype=np.float64)[:, None]                              # [M,1]
    ang = pos * inv_freq[None, :]                                             # [M,HALF]
    cos_h = np.cos(ang).astype(np.float32)
    sin_h = np.sin(ang).astype(np.float32)
    cos_full = np.concatenate([cos_h, cos_h], axis=1).astype(np.float32)      # [M,N]
    sin_full = np.concatenate([sin_h, sin_h], axis=1).astype(np.float32)

    # Golden RoPE(matmul), float32 math, bf16-truncate -- matches kernel bit for bit.
    Cf = bf16_to_f32(C_bf16)                                                  # [M,N] f32
    c0 = Cf[:, :HALF]
    c1 = Cf[:, HALF:]
    cs = cos_h
    sn = sin_h
    o0 = (c0 * cs - c1 * sn).astype(np.float32)
    o1 = (c1 * cs + c0 * sn).astype(np.float32)
    gold = np.empty((M, N), dtype=np.uint16)
    gold[:, :HALF] = f32_to_bf16_trunc(o0)
    gold[:, HALF:] = f32_to_bf16_trunc(o1)

    cos_bits = cos_full.view(np.uint32).reshape(M, N)
    sin_bits = sin_full.view(np.uint32).reshape(M, N)

    with open(HERE / "data", "w") as f:
        f.write("// @generated by gen_data.py -- fused QKV(MX fp4 K=2048) + RoPE(SIMT), head_dim=64\n")
        f.write("#include <stdint.h>\n")
        f.write(f"#define MATMUL_M {M}\n#define MATMUL_N {N}\n#define MATMUL_K {K}\n")
        f.write(f"#define MATMUL_GK {GK}\n#define MATMUL_GN {GN}\n")
        f.write(f"#define VERIFY_COUNT {M * N}\n")
        emit(f, "uint8_t", "A_in_hw", "[MATMUL_M / 2][MATMUL_K]", A_hw)
        emit(f, "uint8_t", "B_in", "[MATMUL_K][MATMUL_N / 2]", B_in)
        emit(f, "uint8_t", "A_scales_row", "[MATMUL_GK][MATMUL_M]", SA)
        emit(f, "uint8_t", "B_scales_col", "[MATMUL_GK][MATMUL_N]", SB)
        emit(f, "uint32_t", "cos_bits", "[MATMUL_M][MATMUL_N]", cos_bits)
        emit(f, "uint32_t", "sin_bits", "[MATMUL_M][MATMUL_N]", sin_bits)
        f.write("__global uint16_t C_raw[MATMUL_M * MATMUL_N] = {0};\n")
        emit(f, "uint16_t", "gold_raw", "[MATMUL_M * MATMUL_N]", gold)
        f.write("static const uint8_t *A_in = &A_in_hw[0][0];\n")
        f.write("static const float* cos_raw = (const float*)&cos_bits[0][0];\n")
        f.write("static const float* sin_raw = (const float*)&sin_bits[0][0];\n")
        f.write("__global float tls_guard[1024] = {0};\n")
    print(f"wrote data  M={M} N={N} K={K} GK={GK} GN={GN} HALF={HALF}")


if __name__ == "__main__":
    if not MX_GOLDEN.exists():
        raise SystemExit(f"build mx_golden first: {MX_GOLDEN}")
    main()
