#!/usr/bin/env python3
"""Generate mxgemm.data.<fmt>.m<M>n<N>k<K>.h headers for the standalone MX kernels.

The gemm_mxgemmini kernels #include a data header that carries the operands, the e8m0 block
scales, and the GOLDEN output. Only fp8 m64n64k64 was ever committed, so every other kernel
variant (128x128x512, 256x256x256, ...) could not even build. This regenerates them.

The golden comes from autocomp's `mx_golden`, which implements the HARDWARE accumulation
semantics (16-deep systolic array with the acc_e/acc_m precision schedule, one e8m0 scale per
32-element K group). It is validated bit-exact against BOTH real spike libgemmini AND the
upstream lib/mxgemmini golden model (see autocomp scripts/muon/xcheck_upstream_golden.py).
Do NOT substitute an idealized numpy/torch matmul: it disagrees with silicon on ~90% of
elements.

Operand magnitudes are capped (|a| <= 1) on purpose: with unrestricted fp8 (|a| up to 448) a
long dot product saturates the e4 block accumulators and essentially every golden element
comes out +/-inf -- a golden that any broken kernel "matches".

Usage:
  ./gen_mxgemm_data.py fp8 64 64 128      # one shape
  ./gen_mxgemm_data.py --all-fp8          # every missing fp8 header
"""
import pathlib
import subprocess
import sys

import numpy as np

HERE = pathlib.Path(__file__).resolve().parent
MX_GOLDEN = pathlib.Path(
    "/scratch/agustin/projects/autocomp/scripts/muon/mx_golden/mx_golden"
)
GROUP = 32
FMT_CODE = {"fp8": 0, "fp6": 1, "fp4": 2}

# Shapes the committed kernels #include but that have no header.
MISSING_FP8 = [(64, 64, 128), (64, 64, 512), (128, 128, 128),
               (128, 128, 256), (128, 128, 512), (256, 256, 256)]


def rand_fp8(rng, n):
    """Random fp8 e4m3 codes with |value| <= 1 (exp field <= bias)."""
    exp = rng.integers(0, 8, size=n, dtype=np.uint8)
    mant = rng.integers(0, 8, size=n, dtype=np.uint8)
    sign = rng.integers(0, 2, size=n, dtype=np.uint8)
    return ((sign << 7) | (exp << 3) | mant).astype(np.uint8)


def emit(f, ctype, name, dims, arr):
    f.write(f"static const {ctype} {name}{dims} = {{\n")
    w = 2 if ctype == "uint8_t" else 4
    rows = ["    { " + ", ".join(f"0x{v:0{w}x}" for v in row) + " }" for row in arr]
    f.write(",\n".join(rows))
    f.write("\n};\n")


def gen(fmt, M, N, K):
    assert fmt == "fp8", "sub-byte (fp4/fp6) packing + LUTs not yet supported here"
    GK, GN = K // GROUP, N // GROUP
    rng = np.random.default_rng(hash((fmt, M, N, K)) & 0xFFFFFFFF)

    A = rand_fp8(rng, M * K).reshape(M, K)
    B = rand_fp8(rng, K * N).reshape(K, N)
    # e8m0 scale codes near 1.0 (0x7f == 2^0)
    SA = rng.integers(0x7B, 0x83, size=(GK, M), dtype=np.uint8)
    SB = rng.integers(0x7B, 0x83, size=(GK, N), dtype=np.uint8)

    tmp = HERE / "_gen" / f"{fmt}_{M}_{N}_{K}"
    tmp.mkdir(parents=True, exist_ok=True)
    (tmp / "A.bin").write_bytes(A.tobytes())
    (tmp / "B.bin").write_bytes(B.tobytes())
    (tmp / "SA.bin").write_bytes(SA.tobytes())
    (tmp / "SB.bin").write_bytes(SB.tobytes())

    def run_golden(out_fmt, cbin, sbin=None):
        env = {"PATH": "/usr/bin:/bin"}
        if out_fmt is not None:
            env["MX_OUT_FMT"] = str(out_fmt)
            if sbin:
                env["MX_SCALES_OUT"] = str(sbin)
        subprocess.run(
            [str(MX_GOLDEN), str(M), str(N), str(K), str(tmp / "A.bin"), str(tmp / "B.bin"),
             str(tmp / "SA.bin"), str(tmp / "SB.bin"), str(cbin), str(FMT_CODE[fmt])],
            check=True, env=env,
        )

    run_golden(None, tmp / "C_bf16.bin")                                  # fullout bf16
    run_golden(0, tmp / "C_q.bin", tmp / "C_scales.bin")                  # requant to fp8
    C_bf16 = np.frombuffer((tmp / "C_bf16.bin").read_bytes(), dtype="<u2").reshape(M, N)
    C_q = np.frombuffer((tmp / "C_q.bin").read_bytes(), dtype=np.uint8)[: M * N].reshape(M, N)
    C_sc = np.frombuffer((tmp / "C_scales.bin").read_bytes(), dtype=np.uint8)[: M * GN]
    C_sc = C_sc.reshape(M, GN).T.copy()  # header wants [GN][M]

    out = HERE / f"mxgemm.data.{fmt}.m{M}n{N}k{K}.h"
    guard = f"MXGEMM_DATA_{fmt.upper()}_M{M}N{N}K{K}_H"
    with open(out, "w") as f:
        f.write(f"// @generated by gen_mxgemm_data.py -- do not edit\n")
        f.write(f"// golden from autocomp mx_golden (hardware semantics; bit-exact vs spike\n")
        f.write(f"// and vs the upstream lib/mxgemmini golden model)\n")
        f.write(f"#ifndef {guard}\n#define {guard}\n\n#include <stdint.h>\n\n")
        f.write(f"#define MATMUL_M {M}\n#define MATMUL_K {K}\n#define MATMUL_N {N}\n")
        f.write(f"#define MATMUL_GK {GK}\n#define MATMUL_GN {GN}\n\n")
        emit(f, "uint8_t", "A_in", "[MATMUL_M][MATMUL_K]", A)
        emit(f, "uint8_t", "B_in", "[MATMUL_K][MATMUL_N]", B)
        emit(f, "uint8_t", "A_scales_row", "[MATMUL_GK][MATMUL_M]", SA)
        emit(f, "uint8_t", "B_scales_col", "[MATMUL_GK][MATMUL_N]", SB)
        emit(f, "uint8_t", "C_out", "[MATMUL_M][MATMUL_N]", C_q)
        emit(f, "uint8_t", "C_scales_row", "[MATMUL_GN][MATMUL_M]", C_sc)
        emit(f, "uint16_t", "C_out_bf16", "[MATMUL_M][MATMUL_N]", C_bf16)
        f.write(f"\n#endif // {guard}\n")
    print(f"wrote {out.name}  (M={M} N={N} K={K} GK={GK} GN={GN})")


if __name__ == "__main__":
    if not MX_GOLDEN.exists():
        raise SystemExit(f"build mx_golden first: {MX_GOLDEN}")
    if sys.argv[1:2] == ["--all-fp8"]:
        for M, N, K in MISSING_FP8:
            gen("fp8", M, N, K)
    else:
        fmt, M, N, K = sys.argv[1], *map(int, sys.argv[2:5])
        gen(fmt, M, N, K)
