#!/usr/bin/env python3
"""Generate deterministic data for the shared-buffer Radiance chain check."""

from pathlib import Path

import numpy as np


def emit(name: str, values: np.ndarray) -> str:
    flat = values.astype(np.float32).ravel()
    def literal(value: float) -> str:
        item = f"{float(value):.9g}"
        return (item if "." in item or "e" in item else item + ".0") + "f"
    literals = ", ".join(literal(value) for value in flat)
    return f"__global float {name}[{len(flat)}] = {{{literals}}};\n"


def main() -> None:
    rng = np.random.default_rng(12)
    m, k, n = 3, 16, 16
    x = rng.standard_normal((m, k)).astype(np.float32) * 0.2
    gamma = 1 + rng.standard_normal(k).astype(np.float32) * 0.1
    weight = rng.standard_normal((k, n)).astype(np.float32) * 0.1
    bias = rng.standard_normal(n).astype(np.float32) * 0.03
    skip = rng.standard_normal((m, n)).astype(np.float32) * 0.1
    eps = 1e-5
    norm = x / np.sqrt(np.mean(x * x, axis=1, keepdims=True) + eps) * gamma
    projected = norm @ weight + bias
    output = projected + skip
    header = ("// Generated by gen_data.py; input and intermediate buffers are distinct.\n"
              f"#define CHAIN_M {m}\n#define CHAIN_K {k}\n#define CHAIN_N {n}\n"
              f"#define CHAIN_EPS {eps:.9g}f\n")
    for name, value in (("input_raw", x), ("gamma_raw", gamma),
                        ("weight_raw", weight), ("bias_raw", bias),
                        ("skip_raw", skip), ("gold_norm_raw", norm),
                        ("gold_projected_raw", projected),
                        ("gold_raw", output)):
        header += emit(name, value)
    Path(__file__).with_name("data").write_text(header)


if __name__ == "__main__":
    main()
